import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Footer from "../common/Footer";
import Header from "../common/Header";
import MainLayout from "../../../MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// ${geistMono.variable}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
      <MainLayout>
           <Header/>
           {children}
          <Footer/>
      </MainLayout>
        
        
      </body>
    </html>
  );
}
